seed = 45

[data]
type = "injection"
detectors = ["ET"]
trigger_time = 1766797218
duration = 180.0
sampling_frequency = 4096.0
zero_noise = true
noise_seed = 0

[data.asd_files]
ET = "curves_Jan_2020/et_d.txt"




[data.injection_parameters]
M_c     = 1.186
eta     = 0.248
s1_z    = 0.005
s2_z    = 0.005
iota    = 2.53
d_L     = 100.0
t_c     = 0.0
phase_c = 0.0
psi     = 1.75
ra      = 3.446
dec     = -0.408
lambda_1 = 300.0
lambda_2 = 450.0

[waveform]
approximant = "IMRPhenomD_NRTidalv2"
f_ref = 20.0

[prior]
M_c     = { type = "uniform",   min = 1.150,  max = 1.250  }
q       = { type = "uniform",   min = 0.125, max = 1.0   }
s1_z    = { type = "uniform",   min = -0.99, max = 0.99  }
s2_z    = { type = "uniform",   min = -0.99, max = 0.99  }
iota    = { type = "sine" }
d_L     = { type = "power_law", min = 1.0,   max = 150.0, alpha = 2.0 }
t_c     = { type = "uniform",   min = -1.0,  max = 1.0   }
phase_c = { type = "uniform",   min = 0.0,   max = 6.283185307179586 }
psi     = { type = "uniform",   min = 0.0,   max = 3.141592653589793 }
lambda_1 = { type = "uniform",   min = 0.0,   max = 1000.0}
lambda_2 = { type = "uniform",   min = 0.0,   max = 1000.0}

[likelihood]
f_min = 20.0
f_max = 2048.0

[likelihood.heterodyne]
# Binning: specify at most one of the two options below.
# epsilon = 0.5  # max phase change per bin in rad (default when neither is set)
n_bins = 5000    # fixed bin count (mutually exclusive with epsilon)

[likelihood.fixed_parameters]
ra = 3.446
dec = -0.408

[sampling]
sky_frame = "geocentric"
time_frame = "geocentric"

[sampler]
type = "blackjax-ns-aw"
n_live = 2000
n_delete_frac = 0.5
n_target = 120


[output]
dir = "/home/ovbenthem/DATA/inj_ET_rel_bin_NS_AW_no_noise_fix"
save_corner = true
overwrite = true 
